[ORG-1] Project initialization
NIRMA-PATIENT-INTAKE/disease pull request #1
Opened 2023-01-09 18:38 UTC by EgorovM

2023-01-12 21:56 UTC, DmitryPogrebnoy requested changes

2023-01-12 21:56 UTC, DmitryPogrebnoy commented on make.bat
> +@ECHO OFF
Почему мы используем Sphinx для генерации документации? Ведь он требует всякие конфиги и кажется довольно избыточный/сложный для такого проекта.
Дефолтным генератором является pydoc - https://docs.python.org/3/library/pydoc.html. Максимально прост, никакие конфиги не нужны. Почему бы не взять его?

2023-01-12 21:56 UTC, DmitryPogrebnoy commented on examples/pipeline_example.py
> +diseases = ["гастрит", "отит", "-1"]
Что такое -1?

2023-01-12 21:56 UTC, DmitryPogrebnoy commented on README.md
>  # Классификатор заболеваний
Какую версию питона используем? 3.11.1? Было бы здорово написать это сразу в ридми

2023-01-12 21:56 UTC, DmitryPogrebnoy commented on disease/base/estimators.py
> +from abc import ABC, abstractmethod
Нам точно нужен линтер, который будет бить по рукам когда пишем некрасиво. Можно например использовать pylint. Кажется стоит тоже сразу его сюда добавить.

2023-01-12 21:56 UTC, DmitryPogrebnoy commented on disease/models/__init__.py
> +__all__ = [DiseaseClassifier]
Почему мы здесь экспортируем только DiseaseClassifier, а не все? Мб стоит убрать и если нужно добавить потом?

2023-01-13 17:14 UTC, EgorovM commented on examples/pipeline_example.py
> +diseases = ["гастрит", "отит", "-1"]
Хотелось бы классифицировать, что нет болезни:)
Это я для себя пытался расписать все кейсы которые могут быть

2023-01-13 17:15 UTC, EgorovM commented on README.md
>  # Классификатор заболеваний
Да, согласен. С другой стороны некоторые ML-ные либы не поддерживают питон старших версий, поэтому я тут пока не решился какой именно брать. Можем вместе подумать

2023-01-13 17:15 UTC, EgorovM commented on disease/base/estimators.py
> +from abc import ABC, abstractmethod
Да, согласен, давай)

2023-01-13 17:19 UTC, EgorovM commented on disease/models/__init__.py
> +__all__ = [DiseaseClassifier]
Давай пока оставим, если будет сильно мешать - уберем. Как мне кажется лучше сразу рассмотреть возможность импортирования через *

2023-01-13 17:35 UTC, EgorovM commented on make.bat
> +@ECHO OFF
Хмм, а ты не знаешь, с помощью pydoc-а можно шейрить документацию без своего сервера? С sphinx можно выложить документацию в сервис Read The Docs бесплатно. Как мне кажется, sphinx мы не будет сильно эксплуатировать, нам хватит и то, что оно генерирует документации к классам. Можем обсудить этот момент еще отдельно.

Спасибо за комментарии!

2023-01-17 17:27 UTC, DmitryPogrebnoy approved these changes

2023-01-18 06:34 UTC, merged