Speedup SymptomExtractor
NIRMA-PATIENT-INTAKE/disease pull request #13
Opened 2023-03-27 20:48 UTC by DmitryPogrebnoy

Performance increased about 2-2.5 times

2023-03-28 06:16 UTC, EgorovM requested changes
Давай попробуем поискать где еще ускорить, но 2-2.5 раза выглядит суперски!

2023-03-28 06:16 UTC, EgorovM commented on distool/feature_extraction/extractors.py
> -        negex_doc: Doc = self._negex_model(model_doc)
оно теперь точно будет доставать отрицания?

2023-03-28 07:51 UTC, DmitryPogrebnoy commented on distool/feature_extraction/extractors.py
> -        negex_doc: Doc = self._negex_model(model_doc)
Точно. Теперь Negex встроен в пайплайн spacy - диф выше

2023-04-01 07:29 UTC, EgorovM approved these changes

2023-04-01 07:30 UTC, merged