Create showcase for computing metrics
NIRMA-PATIENT-INTAKE/disease pull request #14
Opened 2023-04-28 20:36 UTC by DmitryPogrebnoy

2023-05-11 16:24 UTC, EgorovM requested changes

2023-05-11 16:24 UTC, EgorovM commented on distool/metrics/create_showcase.py
> +def main():
давай сделаем так, чтобы можно было передавать инстанс SymptomExtractor-а. Плюс чтобы можно было опционально сохранить датафрейм, и чтобы всегда функция возращала showcase. Хочется это сделать чтобы быстро проверять в чем extractor ошибается. Давай еще как нибудь укажем, что это showcase для extrator-а, а не для чего то другого. Следовательно стоит переименовать функцию.

2023-05-12 09:58 UTC, DmitryPogrebnoy commented on distool/metrics/create_showcase.py
> +def main():
Вроде пофиксил

2023-05-13 07:49 UTC, EgorovM approved these changes

2023-05-13 07:49 UTC, merged