Introduce symptom estimator transformation based on the spacy tree an…
NIRMA-PATIENT-INTAKE/disease pull request #2
Opened 2023-01-27 22:18 UTC by DmitryPogrebnoy

…d negspacy

2023-01-28 09:23 UTC, EgorovM requested changes
Получилось круто, там пару некритичных моментов исправить и можно спокойно заливать)

2023-01-28 09:23 UTC, EgorovM commented on disease/feature_extraction/extractors.py
> +from negspacy.negation import Negex
Кажется не инициализировать pre-commit:)
`pre-commit install`

Импорты не по pep8: https://peps.python.org/pep-0008/#imports

2023-01-28 09:23 UTC, EgorovM commented on disease/feature_extraction/extractors.py
> +        self._negex_model: Negex = Negex(self._spacy_lang_model, "test", SymptomExtractor.russian_termset,
Давай если слишком много атрибутов задается, писать по одному атрибуту в строку и в идеале с названиями атрибутов

Negex(
    nlp=self._speacy_lang_model,
    name="test",
    ...
)

(названия я взял от ба

2023-01-28 09:23 UTC, EgorovM commented on disease/feature_extraction/extractors.py
> +        if entities:
а это проверка точно нужна, если мы потом проверяем symptom in enities?

2023-01-28 09:23 UTC, EgorovM commented on disease/feature_extraction/extractors.py
> +        # Проверяем есть ли в entities симптомы и проставляем соответствующие метки
Пока не критично, но нам бы хотелось писать комментарии на английском

2023-01-28 09:23 UTC, EgorovM commented on disease/feature_extraction/extractors.py
> +                    message_disease[token.lemma_] = -1
Как будто эти условия можно объединить, если выполняют одинаковый код

2023-01-28 09:23 UTC, EgorovM commented on disease/tests/extractors/test_symptom_extractor.py
> +                         "Extracted disease vector is incorrect")
я обычно пишу по одному аргументу на каждую строчку

self.assertEqual(
    disease_vector,
    [-1, -1, 0],
    "Extracted disease vector is incorrect"
)

2023-01-28 09:23 UTC, EgorovM commented on disease/tests/extractors/test_symptom_extractor.py
> +class SymptomExtractorTest(unittest.TestCase):
Красота! Я даже совсем забыл про тесты, приятно удивлен)
Но мы вроде договаривались писать тесты на pytest:)

2023-01-28 09:23 UTC, EgorovM commented on disease/tests/extractors/test_symptom_extractor.py
> +    def test_transform_1(self):
у pytest есть нейминг типа test_\_имя\_функции\__on\_условие\__should\_чтото\_сделать. это позволит понять, что делает тест, не вникая в его код

2023-01-30 20:11 UTC, DmitryPogrebnoy commented on disease/feature_extraction/extractors.py
> +        # Проверяем есть ли в entities симптомы и проставляем соответствующие метки
Комментарии на англ, а ридми на русском?

2023-01-30 20:14 UTC, DmitryPogrebnoy commented on disease/feature_extraction/extractors.py
> +from negspacy.negation import Negex
А ну да, я забыл. Мб тогда еще Github Actions настроим, чтобы было видно что все ок?

2023-01-30 20:15 UTC, DmitryPogrebnoy commented on disease/feature_extraction/extractors.py
> +        self._negex_model: Negex = Negex(self._spacy_lang_model, "test", SymptomExtractor.russian_termset,
oke

2023-01-30 20:23 UTC, DmitryPogrebnoy commented on disease/feature_extraction/extractors.py
> +from negspacy.negation import Negex
Чтобы там тесты гонялись тоже

2023-01-30 20:31 UTC, DmitryPogrebnoy commented on disease/tests/extractors/test_symptom_extractor.py
> +                         "Extracted disease vector is incorrect")
пофиксил

2023-01-30 20:31 UTC, DmitryPogrebnoy commented on disease/feature_extraction/extractors.py
> +        if entities:
А это и не работает лол

2023-01-30 20:32 UTC, DmitryPogrebnoy commented on disease/tests/extractors/test_symptom_extractor.py
> +class SymptomExtractorTest(unittest.TestCase):
Ага, я чет на автомате unittest использовал, поправил

2023-01-30 20:57 UTC, DmitryPogrebnoy commented on disease/tests/extractors/test_symptom_extractor.py
> +    def test_transform_1(self):
oke

2023-01-30 20:58 UTC, DmitryPogrebnoy commented on disease/feature_extraction/extractors.py
> +                    message_disease[token.lemma_] = -1
Это убрал, потому что сущностей хватит

2023-01-30 20:59 UTC, DmitryPogrebnoy commented on disease/feature_extraction/extractors.py
> +        if entities:
Чтобы лишний раз не проверять. Если сущностей нет, то ничего делать не нужно

2023-02-04 09:55 UTC, EgorovM commented on disease/feature_extraction/extractors.py
> +        # Проверяем есть ли в entities симптомы и проставляем соответствующие метки
либо на англ, либо на русском, пока сам не разобрался)
Но в любом случае не стоит комбинить

2023-02-04 09:56 UTC, EgorovM approved these changes

2023-02-04 09:56 UTC, merged