Pogrebnoy/diseases classes
NIRMA-PATIENT-INTAKE/disease pull request #6
Opened 2023-02-11 23:19 UTC by DmitryPogrebnoy

2023-02-13 13:21 UTC, EgorovM requested changes

2023-02-13 13:21 UTC, EgorovM commented on disease/feature_extraction/symptom.py
> +        if isinstance(other, Symptom):
давай лучше сначала проверим not isinstance, вернем False, а дальше будем проверять уже поля

или в одну строчку: isinstance(other, Symptom) and self.id_name == other.id_name 
(на самом деле раз у нас определен хеш, можно наверное не преопределять __eq__

2023-02-13 13:21 UTC, EgorovM commented on disease/feature_extraction/extractors.py
> +    def transform(self, message: str) -> Anamnesis:
кстати я только заметил, нам бы хотелось бы в SymptomExtractor передавать список сообщений и получить батч ответов. def transform(self, message: List[str]) -> List[Anamnesis]:

2023-02-13 13:21 UTC, EgorovM commented on disease/feature_extraction/symptom_collection.py
> +def get_symptoms_patterns() -> List[Dict]:
может в этом файле определим SYMPTOMS_PATTERNS = get_symptoms_patterns() и будем импортировать SYMPTOMS_PATTERNS?

2023-02-13 13:21 UTC, EgorovM commented on disease/feature_extraction/anamnesis.py
> +        self._symptoms_marks: Dict[Symptom, SymptomStatus] = _create_symptoms_marks()
А этот метод нам нужен?

2023-02-13 13:21 UTC, EgorovM commented on disease/feature_extraction/anamnesis.py
> +        self._symptoms_marks: Dict[Symptom, SymptomStatus] = _create_symptoms_marks()
думаю тут можно сразу dict.fromkeys(SYMPTOMS, SymptomStatus.NO_INFO)

2023-02-13 13:21 UTC, EgorovM commented on disease/feature_extraction/anamnesis.py
> +    def __init__(self):
кстати давай добавлять -> None

2023-02-13 13:21 UTC, EgorovM commented on disease/feature_extraction/anamnesis.py
> +    def update_symptoms_statuses_by_new_anamnesis(self, new_anamnesis: Span):
кжись тут new_anamnesis: "Anamnesis" ?

2023-02-13 13:21 UTC, EgorovM commented on disease/feature_extraction/anamnesis.py
> +        for (key, new_value) in new_anamnesis._symptoms_marks.items():
обращаться к приватному методу другого объекта как будто бы не ок, давай выделим метод для получения, тип get_symptoms_marks?

2023-02-13 13:21 UTC, EgorovM commented on disease/feature_extraction/anamnesis.py
> +                or old_value == SymptomStatus.CONFUSED
Тут и в других местах можно заменить на old_value in [SymptomStatus.NO_INFO, SymptomStatus.CONFUSED]

2023-02-21 21:02 UTC, DmitryPogrebnoy commented on disease/feature_extraction/symptom.py
> +        if isinstance(other, Symptom):
Поправил eq

2023-02-21 21:05 UTC, DmitryPogrebnoy commented on disease/feature_extraction/extractors.py
> +    def transform(self, message: str) -> Anamnesis:
оке

2023-02-21 21:08 UTC, DmitryPogrebnoy commented on disease/feature_extraction/anamnesis.py
> +        self._symptoms_marks: Dict[Symptom, SymptomStatus] = _create_symptoms_marks()
Пусть пока будет, мб нам нужно будет предусмотреть команду сброса всего что написал пользователь.

2023-02-21 21:09 UTC, DmitryPogrebnoy commented on disease/feature_extraction/anamnesis.py
> +        self._symptoms_marks: Dict[Symptom, SymptomStatus] = _create_symptoms_marks()
_create_symptom_marks() используется в двух местах, так что я бы оставил как есть, чтобы не дублировать

2023-02-21 21:11 UTC, DmitryPogrebnoy commented on disease/feature_extraction/anamnesis.py
> +    def __init__(self):
ок

2023-02-21 21:15 UTC, DmitryPogrebnoy commented on disease/feature_extraction/anamnesis.py
> +    def update_symptoms_statuses_by_new_anamnesis(self, new_anamnesis: Span):
Ага, поправил

2023-02-21 21:18 UTC, DmitryPogrebnoy commented on disease/feature_extraction/anamnesis.py
> +        for (key, new_value) in new_anamnesis._symptoms_marks.items():
Дак это другой объект того же класса и мы можем его вызывать не ничего не боясь испортить

2023-02-21 21:19 UTC, DmitryPogrebnoy commented on disease/feature_extraction/anamnesis.py
> +                or old_value == SymptomStatus.CONFUSED
Поправил

2023-02-21 21:25 UTC, DmitryPogrebnoy commented on disease/feature_extraction/symptom_collection.py
> +def get_symptoms_patterns() -> List[Dict]:
Окей, я поправил. Это всеравно временное решение пока не будем генерить паттерны из файлика

2023-02-22 09:16 UTC, EgorovM commented on disease/feature_extraction/anamnesis.py
> +        for (key, new_value) in new_anamnesis._symptoms_marks.items():
а мы не захотим где то внешне получить эти марки? как будто бы метод и сам нужен

2023-02-22 09:18 UTC, EgorovM requested changes

2023-02-22 09:18 UTC, EgorovM commented on disease/feature_extraction/extractors.py
> +    def transform(self, message: str) -> Anamnesis:
тут вроде не List[Anamnesis] не поменялся:)

2023-02-22 09:21 UTC, EgorovM requested changes

2023-02-22 09:21 UTC, EgorovM commented on disease/feature_extraction/anamnesis.py
> +            if (old_value == SymptomStatus.YES and entity._.negex == False) or (
обычно пишут not `entity._.nexeg` (кстати, а что это за `._` ?)

2023-02-22 22:37 UTC, DmitryPogrebnoy commented on disease/feature_extraction/anamnesis.py
> +            if (old_value == SymptomStatus.YES and entity._.negex == False) or (
Фреймворк на лету генерит новые поля у объекта Span (вроде) и таким образом к ним можно получить доступ

2023-02-22 22:38 UTC, DmitryPogrebnoy commented on disease/feature_extraction/extractors.py
> +    def transform(self, message: str) -> Anamnesis:
Это два разныъ метода

2023-02-22 22:44 UTC, DmitryPogrebnoy commented on disease/feature_extraction/anamnesis.py
> +        for (key, new_value) in new_anamnesis._symptoms_marks.items():
Добавил метод, но я пока хз как мы будем работать с анамнезом

2023-02-24 09:33 UTC, EgorovM requested changes
Давай еще название PR приведем в порядок:
ORG-{номер задачи}: {описание задачи}

2023-02-24 09:33 UTC, EgorovM commented on disease/feature_extraction/extractors.py
> +    def transform(self, messages: List[str]) -> List[Anamnesis]:
мы тут вызываем метод transform внутри transform-а. ты кажется хотел вверхюю функцию переименовать как то?

2023-02-24 09:34 UTC, EgorovM commented on disease/feature_extraction/extractors.py
> +    def transform(self, message: str) -> Anamnesis:
нам бы хотелось чтобы именно transform возвращал Anamnesis

2023-02-26 16:55 UTC, DmitryPogrebnoy commented on disease/feature_extraction/extractors.py
> +    def transform(self, messages: List[str]) -> List[Anamnesis]:
Поправил

2023-02-26 19:33 UTC, EgorovM requested changes

2023-02-26 19:33 UTC, EgorovM commented on disease/feature_extraction/extractors.py
> +    def transform_many(self, messages: List[str]) -> List[Anamnesis]:
давай наоборот сделаем

transform -> transfrom_single
transform_many -> transform

хотелось бы консистенси с sklearn сохранить

2023-02-26 19:33 UTC, EgorovM commented on disease/feature_extraction/anamnesis.py
> +                old_value == SymptomStatus.NO and entity._.negex == True
Давай `entity._.negex == True` -> `entity._.negex` и `entity._.negex == False` -> `not entity._.negex`. Там дальше по методу тоже такие моменты есть

2023-02-26 21:00 UTC, DmitryPogrebnoy commented on disease/feature_extraction/extractors.py
> +    def transform_many(self, messages: List[str]) -> List[Anamnesis]:
поправил

2023-02-26 21:00 UTC, DmitryPogrebnoy commented on disease/feature_extraction/anamnesis.py
> +                old_value == SymptomStatus.NO and entity._.negex == True
Поправил

2023-02-26 22:03 UTC, EgorovM approved these changes

2023-02-26 22:03 UTC, merged